language: node_js
node_js:
  - 12
before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - yarn
script:
  - yarn test
cache:
  yarn: true
  directories:
    - 'node_modules'
